### ISSUE TITLE
Move @babel/parser to dependencies?

### ISSUE THREAD

**Issue by jakebixby** [patricklx/ember-template-tag#11]
I noticed an error where it's failing to find `@babel/parser` during a test.
```
node_modules/.aspect_rules_js/ember-template-tag@2.3.10/node_modules/ember-template-tag/dist/commonjs/template-parser.d.ts(2,31): error TS2307: Cannot find module '@babel/parser' or its corresponding type declarations.
node_modules/.aspect_rules_js/ember-template-tag@2.3.10/node_modules/ember-template-tag/dist/commonjs/transform-embedded-templates.d.ts(2,30): error TS2307: Cannot find module '@babel/parser' or its corresponding type declarations.
``` 
Seems it's still imported in the esm bundle:
<img width="746" alt="Screen Shot 2023-09-04 at 9 06 22 PM" src="https://github.com/patricklx/ember-template-tag/assets/102083128/d11ca16e-79b9-4fc5-b9b5-bce2f0acc59f">

https://github.com/patricklx/ember-template-tag/blob/main/lib/template-parser.ts#L10
https://github.com/patricklx/ember-template-tag/blob/main/lib/transform-embedded-templates.ts#L27

More than happy to make a PR, just wanted to know how you'd prefer fixing it.

**Comment by patricklx** [comment]
Hi, thanks.
I wanted to remove it from deps, as i just copy it over and patch it... 
I think, either
* just use any, most people will not need this anyway 
* also copy the types
* do some typeof function param from the source
