### ISSUE TITLE
Incompatible with the browser, tries to require `fs`

### ISSUE THREAD

**Issue by NullVoxPopuli** [patricklx/ember-template-tag#2]
the non-@babel/standalone dependencies, in particular `@babel/core`, attempts to load `fs`, which doesn't exist in the browser.

**Comment by patricklx** [comment]
Mmmm, there is a browser version: https://cdnjs.com/libraries/babel-core

Just need to look how to set it up to use that an include in in the target for browser and publish a multi target package

**Comment by NullVoxPopuli** [comment]
`@babel/standalone` is the babel-recommended way to use babel in the browser: https://babeljs.io/docs/babel-standalone

I'm not sure how you'd both use `@babel/standalone` and not depending on targets. maybe a small rollup plugin to swap out the imports when building for browser? idk.
The other thing is that both node and browser support ESM, and package.json#exports doesn't let you differentiate between node and browser. 🙃

**Comment by patricklx** [comment]
Ah, this happens when using esm in the browser. So publish a second version which is only for browser...

**Comment by patricklx** [comment]
it should also work if you add `fs: false`
here: 
https://github.com/NullVoxPopuli/limber/blob/479380c7dc33cc9b44d74249e14f0b9a66fdc3c2/apps/repl/ember-cli-build.js#L123

**Comment by patricklx** [comment]
fixed in https://github.com/patricklx/ember-template-tag/commit/c43fa55b01f666411170d8303e9ae2c5891643c3.
you can now import via 
```js
import { } from 'ember-template-tag/browser-esm';
```

**Comment by patricklx** [comment]
The browser version is built with webpack... It has a lower size than including standalone

**Comment by NullVoxPopuli** [comment]
I gave this another go -- but was unsuccessful -- was the above change released? https://www.npmjs.com/package/ember-template-tag?activeTab=code
not seeing `browser-esm` anywhere

**Comment by patricklx** [comment]
it should also work if you add `fs: false`
here:
https://github.com/NullVoxPopuli/limber/blob/479380c7dc33cc9b44d74249e14f0b9a66fdc3c2/apps/repl/ember-cli-build.js#L123
Or import `ember-template-tag/browser`. Is that not in there?

**Comment by patricklx** [comment]
Yeah, forgot to build it... But with fs: false the size is smaller as the browser build includes glimmer as well.
