### ISSUE TITLE
@babel/traverse security vulnerability

### ISSUE THREAD

**Issue by andreyfel** [patricklx/ember-template-tag#80]
@babel/traverse below 7.23.2 is vulnerable.
https://github.com/advisories/GHSA-67hx-6x53-jw92
All the apps updated to ember-cli 5.5.0 became vulnerable.
This package should allow ranges in the dependencies instead of locked versions.

**Comment by valterfab** [comment]
@patricklx Any ETA on this?

**Comment by mkszepp** [comment]
@patricklx would be great to update this dependency
